admins/urls.py
from django.urls import path
from admins import views

app_name = 'admins'
urlpatterns = [
        path('', views.index, name="home"),
        path('update/<movie_id>/', views.update, name="update"),
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path("admins/", include("admins.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name="home"),
    path('film', views.film, name="film"),
    path('rating', views.rating,name="rating"),
    path('show/<movie_id>/', views.show,name="show"),
    path('contact', views.contact,name="contact"),
    path("addreview",views.add_review,name="addreview")
]

admins/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models


class Movie_model(models.Model):
    title = models.CharField('title', max_length=50)
    rating = models.FloatField('rating')
    year = models.IntegerField('year')
    director = models.CharField('director', max_length=50)
    description = models.TextField()
    img = models.ImageField(upload_to='images/', blank=True, null=True)
    link = models.CharField('link', max_length=200)
    visit_count = models.IntegerField('count', default=0)

    def __str__(self):
        return self.title


class Review(models.Model):
    name_user = models.CharField(max_length=50)
    date = models.DateTimeField(auto_now_add=True)
    description = models.TextField()
    movie = models.ForeignKey(Movie_model, on_delete=models.CASCADE)

    def __str__(self):
         return self.name_user

admins/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.shortcuts import redirect
from main.models import Movie_model,Review
from django.urls import reverse


def index(request):
    movie_list = Movie_model.objects.all()
    return render(request, 'admins/index.html',{'movie_list': movie_list})

def update(request, movie_id):
    movie = Movie_model.objects.get(pk=movie_id)
    return render(request, 'admins/update.html',{'movie': movie})

main/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.shortcuts import redirect
from .models import Movie_model, Review
from django.urls import reverse


def index(request):
    movie_list = Movie_model.objects.all()
    return render(request, 'main/index.html', {'movie_list': movie_list})


def film(request):
    movie_list = Movie_model.objects.all()
    return render(request, 'main/films.html',{'title':'Фильмы','movie_list': movie_list})


def rating(request):
    return render(request, 'main/rating.html')


def show(request, movie_id):
    movie = Movie_model.objects.get(pk=movie_id)
    movie.visit_count +=1
    movie.save()
    revier_list = movie.review_set.all().order_by("-date")

    print(movie.review_set.all())
    return render(request, 'main/show.html',{'movie': movie,"revier_list":revier_list})


def contact(request):
    return render(request, 'main/contact.html')


def add_review(request):
    print(request.POST)
    movie = Movie_model.objects.get(pk=request.POST["movie"])
    review = Review(name_user=request.POST['review_name'], description=request.POST["review_text"], movie=movie)
    review.save()
    return HttpResponseRedirect(reverse('main:show', args=[request.POST["movie"]]))

templates/admins/index.html
<!doctype html>
{% load static %}
<html class="no-js" lang="">

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'admins/css/style.css' %}">
    <meta charset="utf-8">
    <title>Админка</title>
    <meta name="description" content="админка">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Стили -->

    <!-- Приводим стили к общему виду с помощью https://github.com/necolas/normalize.css -->
    <link rel="stylesheet" href="css/normalize.css">

    <link rel="stylesheet" href="css/main.css">

    <!-- Font Awesome иконки -->
    <script src="https://kit.fontawesome.com/4a23243fb41.js" crossorigin="anonymous"></script>

    <!-- jQuery и скрипты -->
    <script src="js/vendor/jquery-3.4.1.min.js"></script>
    <script src="js/main.js"></script>

</head>
<body>
    <!-- Главный контейнер -->
    <div class="container">

        <!-- Заголовок -->
        <header class="dashboard-header">
            <h1 class="dashboard-header__logo">Админка</h1>
        </header>

        <!-- Левое меню -->
        <nav class="sidebar-menu">
            <ul class="sidebar-menu__items">
                <li class="sidebar-menu__item">
                    <a href="#" class="sidebar-menu__item-title">
                        <span>Общие</span>
                        <i class="fas fa-caret-down"></i>
                    </a>
                    <ul class="sidebar-menu__subitems">
                        <li class="sidebar-menu__subitem">
                            <a href="/section.html">
                                <i class="fas fa-list-ul"></i>
                                <span>Разделы</span>
                            </a>
                        </li>
                        <li class="sidebar-menu__subitem">
                            <a href="/subsection.html">
                                <i class="fas fa-stream"></i>
                                <span>Категории</span>
                            </a>
                        </li>
                        <li class="sidebar-menu__subitem">
                            <a href="#">
                                <i class="fas fa-edit"></i>
                                <span>Статьи</span>
                            </a>
                        </li>
                        <li class="sidebar-menu__subitem">
                            <a href="#">
                                <i class="fas fa-user"></i>
                                <span>Пользователи</span>
                            </a>
                        </li>
                        <li class="sidebar-menu__subitem">
                            <a href="#">
                                <i class="fas fa-photo-video"></i>
                                <span>Медиа</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="sidebar-menu__item">
                    <a href="#" class="sidebar-menu__item-title">
                        <span>Настройки</span>
                        <i class="fas fa-caret-down"></i>
                    </a>
                    <ul class="sidebar-menu__subitems">
                        <li class="sidebar-menu__subitem">
                            <a href="#">
                                <i class="fas fa-database"></i>
                                <span> Общие</span>
                            </a>
                        </a>
                        </li>
                        <li class="sidebar-menu__subitem">
                            <a href="#">
                                <i class="fas fa-user-friends"></i>
                                <span>Пользователи</span>
                            </a>
                        </li>
                        <li class="sidebar-menu__subitem">
                            <a href="#">
                                <i class="fas fa-comment-alt"></i>
                                <span>Комментарии</span>
                            </a>
                        </li>
                        <li class="sidebar-menu__subitem">
                            <a href="#">
                                <i class="fas fa-info-circle"></i>
                                <span>Статистика</span>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>

        <!-- Главный контент -->
        <main class="main-content">
            <!-- Все содержимое страниц надо помещать здесь -->
        </main>


    </div>


</body>
</html>

templates/admins/update.html
<!doctype html>
{% load static %}
<html class="no-js" lang="">

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'admins/css/style.css' %}">
    <meta charset="utf-8">
    <title>Админка</title>
    <meta name="description" content="админка">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Стили -->

    <!-- Приводим стили к общему виду с помощью https://github.com/necolas/normalize.css -->
    <link rel="stylesheet" href="css/normalize.css">

    <link rel="stylesheet" href="css/main.css">

    <!-- Font Awesome иконки -->
    <script src="https://kit.fontawesome.com/4a23243fb41.js" crossorigin="anonymous"></script>

    <!-- jQuery и скрипты -->
    <script src="js/vendor/jquery-3.4.1.min.js"></script>
    <script src="js/main.js"></script>

</head>
<body>
    <!-- Главный контейнер -->
    <div class="container">

        <!-- Заголовок -->
        <header class="dashboard-header">
            <h1 class="dashboard-header__logo">Админка</h1>
        </header>

        <!-- Левое меню -->
        <nav class="sidebar-menu">
            <ul class="sidebar-menu__items">
                <li class="sidebar-menu__item">
                    <a href="#" class="sidebar-menu__item-title">
                        <span>Общие</span>
                        <i class="fas fa-caret-down"></i>
                    </a>
                    <ul class="sidebar-menu__subitems">
                        <li class="sidebar-menu__subitem">
                            <a href="/section.html">
                                <i class="fas fa-list-ul"></i>
                                <span>Фильмы</span>
                            </a>
                        </li>
                        <li class="sidebar-menu__subitem">
                            <a href="/subsection.html">
                                <i class="fas fa-stream"></i>
                                <span>Категории</span>
                            </a>
                        </li>
                        <li class="sidebar-menu__subitem">
                            <a href="#">
                                <i class="fas fa-edit"></i>
                                <span>Статьи</span>
                            </a>
                        </li>
                        <li class="sidebar-menu__subitem">
                            <a href="#">
                                <i class="fas fa-user"></i>
                                <span>Пользователи</span>
                            </a>
                        </li>
                        <li class="sidebar-menu__subitem">
                            <a href="#">
                                <i class="fas fa-photo-video"></i>
                                <span>Медиа</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="sidebar-menu__item">
                    <a href="#" class="sidebar-menu__item-title">
                        <span>Настройки</span>
                        <i class="fas fa-caret-down"></i>
                    </a>
                    <ul class="sidebar-menu__subitems">
                        <li class="sidebar-menu__subitem">
                            <a href="#">
                                <i class="fas fa-database"></i>
                                <span> Общие</span>
                            </a>
                        </a>
                        </li>
                        <li class="sidebar-menu__subitem">
                            <a href="#">
                                <i class="fas fa-user-friends"></i>
                                <span>Пользователи</span>
                            </a>
                        </li>
                        <li class="sidebar-menu__subitem">
                            <a href="#">
                                <i class="fas fa-comment-alt"></i>
                                <span>Комментарии</span>
                            </a>
                        </li>
                        <li class="sidebar-menu__subitem">
                            <a href="#">
                                <i class="fas fa-info-circle"></i>
                                <span>Статистика</span>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>

        <!-- Главный контент -->
        <main class="main-content">
            <!-- Все содержимое страниц надо помещать здесь -->
            <h1>{{ movie.title }}</h1>
            <form method="post"   action="">
                {% csrf_token %}
                <label for="">Title</label>
                <input type="text" name=" title" value="{{ movie.title }}"><br>
                 <label for="">rating</label>
                <input type="text" name="rating" value="{{ movie.rating}}"><br>
                 <label for="">year</label>
                <input type="text" name="year" value="{{ movie.year}}"><br>
                 <label for="">director</label>
                <input type="text" name="director" value="{{ movie.director}}"><br>
                 <label for="">description</label>
                <input type="text" name="description" value="{{ movie.description}}"><br>
                 <label for="">link</label>
                <input type="text" name="link" value="{{ movie.link}}"><br>
                 <label for="">visit_count</label>
                <input type="text" name="visit_count" value="{{ movie.visit_count}}"><br>
                <input type="submit" name="save" value="save"><br>

            </form>
        </main>


    </div>


</body>
</html>

templates/main/base.html
<!DOCTYRE html>
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="KinoMonster-это портал о кино">
    <meta name="keywords" content="film, online film, hd">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/style.css' %}">
</head>
<body>
<div class="main">
    <div class="header">
        <div class="logo">
            <div class="logo_text">
                <h1><a href="{% url 'main:home' %}">KinoMonster</a></h1>
                <h2>Кино - наша страсть.</h2>
            </div>
        </div>
        <div class="menubar">
            {% block menu %}
            {% endblock %}
        </div>
    </div>
    <div class="site_content">
        <div class="sitebar_container">
            <div class="sidebar">
                <h2>Поиск</h2>
                <form method="post" action="#" id="search_form">
                    <input type="search" name="search_field" placeholder="ваш запрос"/>
                    <input type="submit" class="btn" value="найти"/>
                </form>
            </div>
            <div class="sidebar">
                <h2>Вход</h2>
                <form method="post" action="#" id="login">
                    <input type="text" name="login_field" placeholder="логин">
                    <input type="password" name="password_field" placeholder="пароль">
                    <input type="submit" class="btn" value="ввести">
                    <div class="lables_passreg_text">
                        <span><a href="#">забыли пароль?</a></span> | <span><a href="#">регистрация</a></span>
                    </div>
                </form>
            </div>
            <div class="sidebar">
                <h2>Новости</h2>
                <span>31.02.2020</span>
                <p>Мы запустили расширенный поиск</p>
                <a href="#">читать</a>
            </div>
            <div class="sidebar">
                <h2>Рейтинг фильмов</h2>
                <ul>
                    {% for el in movie_list %}
                        <li><a href="#">{{ el.title }}</a><span class="reting_sidebar">8.1</span></li>

                    {% endfor %}
                </ul>
            </div>
        </div>
        {% block body %}
        {% endblock %}
    </div>

    <div class="footer">
        <p>
            <a href="index.html">Главная</a> |
            <a href="films.html">Фильмы</a> |
            <a href="#">Сериалы</a> |
            <a href="rating.html">Рейтинг фильмов</a> |
            <a href="contact.html">Контакты</a>
        </p>
        <p>wh-db.com 2018</p>
    </div>
</div>
</body>
</html>

templates/main/contact.html
{% extends "main/base.html" %}
{% load static %}

{% block menu %}
     <ul class="menu">
           <li><a href="{% url 'main:home' %}">Главная</a></li>
           <li><a href="{% url 'main:film' %}">Фильмы</a></li>
           <li><a href="{% url 'main:rating' %}">Рейтинг</a></li>
           <li class="selected"><a href="{% url 'main:contact' %}">Контакты</a></li>
  	 </ul>
 {% endblock %}

{% block body %}
      <div class="content">

               <h1>Контакты</h1>
                <p>Отправьте ваш отзыв о портале КиноМонстер</p>

                     <div class="send_contact">

                        <form method="post" action="#" id="contact">

                               <input type="text" name="review_name" placeholder="ваше имя">
                               <input type="text" name="review_email" placeholder="ваше email">
                               <textarea name="review_text"></textarea>
                               <input type="submit" class="btn" value="отправить" >

                        </form>

                     </div>

                 </div>
{%  endblock %}

templates/main/films.html
{% extends "main/base.html" %}
{% load static %}

{% block menu %}
     <ul class="menu">
           <li><a href="{% url 'main:home' %}">Главная</a></li>
           <li class="selected"><a href="{% url 'main:film' %}">Фильмы</a></li>
           <li><a href="{% url 'main:rating' %}">Рейтинг</a></li>
           <li><a href="{% url 'main:contact' %}">Контакты</a></li>
  	 </ul>
 {% endblock %}

{% block body %}
        <div class="content">
           {% for el in movie_list %}

               <div class="info_film">
                 <img src="{{el.img.url}}">
                   <p>{{ el.description }}</p>
                  <div class="button"><a href="{% url 'main:show' el.id %}">Смотреть</a></div>
               </div>

           {% endfor %}



            </div>

{%  endblock %}

templates/main/index.html
{% extends "main/base.html" %}
{% load static %}

{% block menu %}
<ul class="menu">
    <li class="selected"><a href="{% url 'main:home' %}">Главная</a></li>
    <li><a href="{% url 'main:film' %}">Фильмы</a></li>
    <li><a href="{% url 'main:rating' %}">Рейтинг</a></li>
    <li><a href="{% url 'main:contact' %}">Контакты</a></li>
</ul>
{% endblock %}

{% block body %}
<div class="content">

    <h1>Новые фильмы</h1>


    <div class="film_block">
        {% for movie in movie_list %}
        <a href="{% url 'main:show' movie.id %}"><img src="{{movie.img.url}}"></a>
        {% endfor %}
    </div>

    <h1>Новые сериалы</h1>

    <div class="film_block">


    </div>

</div>
<div class="content_info">
    <hr>
    <h1><a href="">Как снимали Интерстеллар</a></h1>
    <div class="post_content">
        <p>45 лет исполнилось Кристоферу Нолану — одному из самых успешных режиссеров нашего времени, чьи работы
            одинаково любимы как взыскательными критиками, так и простыми зрителями. Фильмом изначально занималась
            студия Paramount. Когда Кристофер Нолан занял место режиссера, студия Warner Bros., которая выпускала его
            последние фильмы, добилась участия в проекте.</p>

        <a href="">читать</a>
        <hr>
        <h1><a href="">Актер Том Хенкс поделился впечатлением о фестивале</a></h1>

        <p>16 февраля в Лондоне состоялась 67-я церемония вручения наград Британской киноакадемии. Леонардо ДиКаприо,
            Брэд Питт, Анджелина Джоли, Кейт Бланшетт, Хелен Миррен, Эми Адамс, Кристиан Бэйл, Альфонсо Куарон и другие
            гости и победители премии — в нашем репортаже.</p>
    </div>
    <a href="">читать</a>
</div>
{%  endblock %}

templates/main/rating.html
{% extends "main/base.html" %}
{% load static %}

{% block menu %}
     <ul class="menu">
           <li><a href="{% url 'main:home' %}">Главная</a></li>
           <li><a href="{% url 'main:film' %}">Фильмы</a></li>
           <li class="selected"><a href="{% url 'main:rating' %}">Рейтинг</a></li>
           <li><a href="{% url 'main:contact' %}">Контакты</a></li>
  	 </ul>
 {% endblock %}

{% block body %}
          <div class="content">

                     <table>

          <tr>
            <th></th>
            <th>Фильм</th>
            <th class="center">Год</th>
            <th class="center">Рейтинг</th>
          </tr>
          <tr>
            <td class="center"><img src="{% static 'img/inter.png' %}"></td>
            <td>1. <a href="{% url 'main:show' 1 %}">Интерстеллар</a></td>
            <td class="center">2014</td>
            <td class="center rating">8.1</td>
          </tr>
          <tr>
            <td class="center"><img src="{% static 'img/matrix.png' %}"></td>
            <td>2. <a href="{% url 'main:show' 2 %}">Матрица</a></td>
            <td class="center">1999</td>
            <td class="center rating">8.0</td>
          </tr>
          <tr>
            <td class="center"><img src="{% static 'img/max.png' %}"></td>
            <td>3. <a href="{% url 'main:show' 3 %}">Безумный макс</a></td>
            <td class="center">2015</td>
            <td class="center rating">7.5</td>
          </tr>
          <tr>
            <td class="center"><img src="{% static 'img/cloud.png' %}"></td>
            <td>4. <a href="{% url 'main:show' 4 %}">Облачный атлас</a></td>
            <td class="center">2013</td>
            <td class="center rating">7.4</td>
          </tr>

        </table>

  </div>

{%  endblock %}

templates/main/show.html
{% extends "main/base.html" %}
{% load static %}

{% block menu %}
    <ul class="menu">
        <li><a href="{% url 'main:home' %}">Главная</a></li>
        <li><a href="{% url 'main:film' %}">Фильмы</a></li>
        <li><a href="{% url 'main:rating' %}">Рейтинг</a></li>
        <li><a href="{% url 'main:contact' %}">Контакты</a></li>
    </ul>
    <div>kjhkh!!!!</div>
{% endblock %}


{% block body %}
    <div class="content">

        <h1>{{ movie.title }}</h1>

        <iframe width="560" height="315" src="{{ movie.link }}" frameborder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen></iframe>

        <div class="info_film_page">

            <span class="label">рейтинг: </span><span class="value">{{ movie.rating }}/10</span>
            <span class="label">год: </span><span class="value">{{ movie.year }}</span>
            <span class="label">режиссер: </span><span class="value">{{ movie.director }}</span>
            <span class="label">просмотры: </span><span class="value">{{ movie.visit_count }}</span>

        </div>
        <hr>
        <h2>Описание {{ movie.title }}</h2>
        <div class="description_film">
            <img src="{{ movie.img.url }}">
            {{ movie.description }}
        </div>

        <hr>
        <h2>Отзывы об Интерстеллар</h2>
        {% for revier in revier_list %}
        <div class="reviews">
            <div class="review_name">
                {{ revier.name_user }}
            </div>
            <div class="review_text">
                 {{ revier.description }}
            </div>
        <div> Date:{{ revier.date|date:"Y-m-d, h-m-s" }}</div>
        </div>
        {% endfor %}


        <div class="send">

            <form method="post" action="{% url 'main:addreview' %}" id="review">
                {% csrf_token %}
                <input type="text" name="review_name" placeholder="ваше имя" required>
                <textarea name="review_text" required></textarea>
                <input type="hidden" name ="movie" value="{{ movie.id }}" required>
                <input type="submit" class="btn" value="отправить">

            </form>

        </div>

    </div>

{% endblock %}